# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Social

social: 
  facebook:          paulmmj
  twitter:           PLJNS
  google-plus:       PaulJones93
  foursquare:        PLJNS
  github:            PLJNS
  soundcloud:        PLJNS
  youtube:           paulmmj
  instagram:         PLJNS
  linkedin:          paulmmj
  email:             paulmmj@gmail.com

# Setup
title:            Fekyll Noted
tagline:          'Fekyll with note publishing built-in'
description:      "Fekyll combines the simple, static, and blog-aware power of Jekyll with the most advanced responsive front-end framework in the world, Foundation. Packaged with elegant layouts right of the box, Fekyll is perfect for quickly making your GitHub project or personal page."
url:              http://PLJNS.com

javascript-dir: /public/js
stylesheet-dir: /public/css
images-dir:     /public/img

simple-form: x
disqus: x

author:
  name:           'Your Name'
  url:            http://PLJNS.com

paginate:         5

# Custom vars
version:          1.0.0

# Navigation

navigation:
- text: Blog
  url: /blog/
- text: Notes
  url: /notes/
- text: Projects
  url: /projects/
- text: About
  url: /about/
- text: Contact
  url: /contact/
